# These are supported funding model platforms

github:　[truedat101] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: [https://solscan.io/account/4XJmEJ9XZMiEWTgPK2reYuXK1tLx4XwcqVwXpXUeingp]
