# These are supported funding model platforms

github:　[truedat101] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: [https://www.dial.to/?action=solana-action:https://action.solscan.io/api/donate?receiver=4XJmEJ9XZMiEWTgPK2reYuXK1tLx4XwcqVwXpXUeingp]
